[versions]
agp = "8.9.1"
kotlin = "2.0.21"
godot = "4.3.0.stable"

[libraries]
godot = { module = "org.godotengine:godot", version.ref = "godot" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

